sonar.projectKey=oshadikodagoda_Oshi-Beauty-App
sonar.organization=oshadikodagoda
sonar.projectName=Oshi Beauty App
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src,tests,e2e
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.steps.cjs

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,**/public/**

sonar.typescript.tsconfigPath=tsconfig.app.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info